### PR TITLE
perf(drm): group dracut_instmods calls

### PR DESCRIPTION
**Pull request by jannau**
This module loops over many bus devices, and calls `dracut_instmods` for each one. E.g., on a Lenovo Thinkpad laptop:

```
> for i in /sys/bus/{pci/devices,platform/devices,virtio/devices,soc/devices/soc?,vmbus/devices}/*/modalias; do [[ -e $i ]] && [[ -n $(< "$i") ]]  && echo $i; done | wc -l
79
```

Every call to `dracut_instmods` spawns a `dracut-install` process, which in the previous example means calling `dracut-install` 79 times using the same arguments.

If any call to `dracut-install` fails, dracut continues its execution (even the errors are not shown, because it's called with `--silent`). Therefore, let's take the contents of all the `modalias` files into an array and call `dracut-install` only once, adding also the `-o` argument, so if any of the modules cannot be installed, `dracut-install` does not stop.

(Cherry picked from commit 80f2caf4f5ee47a708b5e4bd65c28e3f8ff1b9c8)

Resolves: rhbz#2172269

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

**Comment by jannau** [comment]
Is there anything to do to get this merged? The failing CI checks are unrelated to the change as far as I can tell.

This 'performance' issue is resulting in broken systems because the initramfs may take more 10 minutes and people are either assuming it is hanging and power cycle their systems.

**Comment by marcan** [comment]
Ping about this again. This is a serious ongoing source of pain for users.

**Comment by jannau** [comment]
to bring the point along why users think their update is hanging:
```
time dracut --force --kver $(uname -r)
real    28m21.147s
user    19m1.308s
sys     9m22.417s
```

**Comment by pvalena** [comment]
Hello, sorry, I must've somehow missed this. I will check my notifications. This is part of rebase to dracut-102, right?

**Comment by marcan** [comment]
Yes, dracut-102 has the patch. In addition, dracut-ng/dracut-ng#328 (trivial patch) dracut-ng/dracut-ng#408 (relatively simple) further improve things, though this change which is already in 102 is the biggest win/major issue.

**Comment by jannau** [comment]
@pvalena do you plan to push dracut-102 soon to Fedora 40? If not please consider to add this change to dracut-101 in Fedora 40. The performance regression on Apple silicon (probably all arm64) systems is severe. We seem to get with every kernel update at least one person who assumed the machine hang and power cycle which leaves the kernel un-bootable due to the missing initramfs image.

**Comment by pvalena** [comment]
> @pvalena do you plan to push dracut-102 soon to Fedora 40? If not please consider to add this change to dracut-101 in Fedora 40. The performance regression on Apple silicon (probably all arm64) systems is severe. We seem to get with every kernel update at least one person who assumed the machine hang and power cycle which leaves the kernel un-bootable due to the missing initramfs image.

Yes, that's the plan: https://src.fedoraproject.org/rpms/dracut/pull-request/60

**Comment by pvalena** [comment]
Merged; building. Please file another PR if you want additional fixes.

**Pull request closed without merging**
